version: '3'  
services:  
  db:
    build: ./db
    # volumes:
    #   - ./db/pgdata:/pgdata
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
  app:
    build: ./backend
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    volumes:
      - ./backend:/go/src/app
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - db