version: '3'  
services:  
  db:
    build: ./db
    # volumes:
    #   - ./db/pgdata:/pgdata
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
  app:
    build: ./backend
    command: gin
    volumes:
      - ./backend:/go/src/app
    ports:
      - "8080:3000"
    depends_on:
      - db
    links:
      - db